---
title: "Association of obstructive sleep apnea with brain volummetry and cognition in de novo Parkinson's disease"
author: "Josef Mana"
date: "`r Sys.Date()`"
format:
  pdf:
    df-print: kable
bibliography: references.bib
---

```{r}
#| label: envir
#| warning: false
#| echo: false

library(tidyverse)
library(here)
library(gt)


```


# Methods

## Neuropsychological assessment

All patients (PD) and healthy controls (HC) were administered a battery of neuropsychological tests at enrollment to the study and subsample of participants were administered the same tests at re-test four years after the enrollment. The battery included assessment of (i) declarative memory via Rey Auditory Verbal Learing Test (RAVLT) [@bezdicek2014; @frydrychova2018], (ii); attention via Trail Making Test, part A (TMT-A) [@bezdicek2012; @bezdicek2017a], and dot colour naming (PST-D) as well as naming colour of neutral words (PST-W) conditions from Prague Stroop Test [@bezdicek2015a]; (iii) executive function via Trail Making Test, part B [@bezdicek2012; @bezdicek2017a], and Prague Stroop Test, interference condition (i.e., naming colour of contrasting colour words, PST-C) [@bezdicek2015a]; and (iv) processing speed via Grooved Pegboard Test (GPT) [@klove1963]. The patients were further examined using tests from the standard International Parkinson and Movement Disorder Society (MDS) neuropsychological battery at Level II for mild cognitive impairment in Parkinson’s disease (PD-MCI) [@litvan2012;  @bezdicek2017]. The Czech normative calculator established by @bezdicek2017 was used to assign PD-MCI diagnosis to each PD patient separately at enrollment and retest. Finally, all participants were yearly administered Montreal cognitive assessment (MoCA) [@kopecek2017; @nasreddine2005] for cognitive screening.

## Statistical analysis

All demographic variables were described by their mean and standard deviation if continuous and frequency if nominal separately for HC OSA-, HC OSA+, PD OSA-, and PD OSA+ groups of participants.

### Cortical thickness

*4 Fíla*

### Subcortical volummetry


### Cognitive variables



# Results

## Sample description

## Cortical thickness

*4 Fíla*

## Subcortical volummetry


## Cognitive variables


# Appendix


# References

