#' Imports raw data
#'
#' Takes in file paths to data and helper files, imports the data and structure
#' them properly.
#'
#' @param files A data.frame containing paths do data files generated by
#' \code{data_paths}.
#' @param helpers A list containing helper files generated by \code{extract_helpers}
#'
#' @exports A tibble containing raw data.
import_data <- function(files, helpers) {
  # Read raw data:
  data <- with(files, {
    list(
      # MRI volummetry estimates
      subcor = read.xlsx(subcor) |>
        rename_with(~gsub("-", "_", .x)) |>
        rename_with(~gsub(",", ".", .x, fixed = TRUE)),
      hippo = left_join(
        read.xlsx(rhippo) |>
          rename_with(~gsub("-", "_", .x)) |>
          mutate(across(!ends_with("ID"), as.numeric)),
        read.xlsx(lhippo) |>
          rename_with(~gsub("-", "_", .x)),
        by = "Study.ID",
        suffix = c("_rhx", "_lhx")
      ),
      mta = read.xlsx(mta) |>
        select(Study.ID, contains("MTA")),
      # Psychology data
      psych = read.csv(psych, sep = ",") |>
        mutate(
          Study.ID = sub("-", "", study_id),
          event = sub("_arm_2|_arm_3", "", redcap_event_name)
        ) |>
        select(Study.ID, event, all_of( c(helpers$psychohelp$variable,"moca"))) |>
        filter(event == "enrollment"),
      # MDS-UPDRS data
      motor = read.xlsx(motor, startRow = 2, check.names = TRUE) |>
        mutate(
          age_first_symptom = time_length(difftime(První.motorický.příznak.PN..MM.RRRR., Datum.narození), "years"),
          disease_duration = time_length(difftime(Datum.vyšetření, První.motorický.příznak.PN..MM.RRRR.), "years"),
          event = "enrollment"
        ) |>
        select(
          Study.ID, event, age_first_symptom, disease_duration,
          MDS.UPDRS.Část.I.sumární.skóre,
          MDS.UPDRS.Část.II.sumární.skóre..počítaná.hodnota.,
          MDS.UPDRS.Část.III..celkové.score., Axiasubscore, Rigidityakinesia, Tremorsubscoret
        ) |>
        rename(
          "mds_updrs_i" = "MDS.UPDRS.Část.I.sumární.skóre",
          "mds_updrs_ii" = "MDS.UPDRS.Část.II.sumární.skóre..počítaná.hodnota.",
          "mds_updrs_iii_total" = "MDS.UPDRS.Část.III..celkové.score.",
          "mds_updrs_iii_axial" = "Axiasubscore",
          "mds_updrs_iii_rigidityakineasia" = "Rigidityakinesia",
          "mds_updrs_iii_tremor" = "Tremorsubscoret"
        )
      ) |>
      # Pull the data to a single file:
      reduce(left_join)
  })
  # Add standardised volumes of subcortical structures:
  with(helpers, {
    for(i in seq_len(nrow(subco))) {
      data[ , subco$scaled[i]] <<- (data[ , subco$name[i]] / data$sBTIV) * mean(data$sBTIV)
    }
  })
  # Prepare objects for PD-MCI labelling:
  calculator <- helpers$calculator |>
    filter(X1 %in% with( helpers$psychohelp, label[!is.na(pairs)])) |>
    mutate(
      sign = if_else(X1 %in% c("TMT-A","PST-C"), -1, 1),
      var = unlist(
        sapply(seq_len(n()), function(i) {
          helpers$psychohelp[helpers$psychohelp$label == X1[i], "variable"]
        }),
        use.names = TRUE
      )
    )
  # Prepare thresholds for BNT-60:
  bnt_thresh <- data.frame(
    age_bottom = c(0, 0, 60, 60),
    age_top = c(60, 60, Inf, Inf),
    edu_bottom = c(0, 12, 0, 12),
    edu_top = c(12, Inf, 12, Inf),
    threshold = c(49, 52, 50, 53)
  )
  # Prepare a table for MoCA (i.e., lvl. I) (based on https://doi.org/10.1080/23279095.2015.1065261):
  moca_thresh <- data.frame(
    age_bottom = c(0, 0, 74, 74),
    age_top = c(74, 74, Inf, Inf),
    edu_bottom = c(0, 12, 0, 12),
    edu_top = c(12, Inf, 12, Inf),
    M = c(24.62, 26.43, 22.98, 24.79),
    SD = c(2.66, 2.37, 2.88, 2.47)
  ) |>
    mutate(threshold = M - 1.5 * SD)
  # Add MCI flag for each test of each patient:
  mci <- data |>
    filter(SUBJ == "PD") |> # keep patients only
    # Add MCI flags (i.e., z ≤ -1.5):
    mutate(
      across(
        .cols = calculator$var,
        .fns = ~zscore(calculator, .x, cur_column(), AGE, GENDER, EDU.Y),
        .names = "z_{.col}"
      ),
      across(
        .cols = starts_with("z_"),
        .fns = ~if_else(.x <= -1.5, 1, 0),
        .names = "mci_{.col}"
      ),
      mci_bnt = sapply(seq_len(n()), function(i) {
        ifelse(
          test = bnt60[i] <= with(bnt_thresh, threshold[AGE[i] > age_bottom & AGE[i] <= age_top & EDU.Y[i] > edu_bottom & EDU.Y[i] <= edu_top] ),
          yes = 1,
          no = 0
        )
      }),
      PDMCI_I = sapply(seq_len(n()), function(i) {
        ifelse(
          test = moca[i] <= with(moca_thresh, threshold[AGE[i] > age_bottom & AGE[i] <= age_top & EDU.Y[i] > edu_bottom & EDU.Y[i] <= edu_top] ),
          yes = 1,
          no = 0
        )
      })
    ) |>
    # Evaluate PD-MCI:
    select(Study.ID, starts_with("mci_"), PDMCI_I) |>
    mutate(
      flags = rowSums(across( starts_with("mci_")), na.rm = TRUE),
      nas = rowSums(is.na( across( starts_with("mci_")))),
      PDMCI_II = case_when(
        flags >= 2 ~ 1,
        flags == 0 & nas < 2 ~ 0,
        flags == 1 & nas == 0 ~ 0,
        .default = NA
      )
    ) |>
    select(Study.ID, PDMCI_I, PDMCI_II)
  # Add PD-MCI to the data and return
  left_join(data, mci)
}
