#' Pre-process the data
#'
#' Takes in raw data, helper files, response times variables and indicator of
#' the object that shall be returned.
#'
#' @param data A data.frame containing raw data generated by
#' \code{import_data}.
#' @param help A list containing helper files generated by \code{extract_helpers}
#' @param rt_vars A
#' @param return A character indicating what shall be returned. Either "df" to
#' return the data or "scl" to return scaling values.
#'
#' @exports A tibble containing raw data.
preprocess_data <- function(data, help, rt_vars, return = "df") {
  # Read the data:
  d0 <- data |>
    # Re-calculate hippocampal fields according to the legend in hippo:
    mutate(
      !!!setNames(rep(NA, length(unique(help$hippo$name))), unique(help$hippo$name)),
      across(
        .cols = unique(help$hippo$name),
        .fns = ~rowSums(across(all_of(with(help$hippo, var[name == cur_column()]))))
      )
    )
  # Format it for analyses:
  df <- d0 |>
    # Pre-process brain and demography variables:
    mutate_if(is.character, as.factor) |>
    mutate(
      PD = if_else(SUBJ == "PD", 1, 0),
      GENDER = as.factor(GENDER),
      across(all_of(rt_vars), ~-log(.x)) # cognition
    ) |>
    # Set-up contrasts to avoid multicollinearity in interaction terms:
    within({
      contrasts(SUBJ) <- -contr.sum(2)/2 # CON = -0.5, PD = 0.5
      contrasts(AHI.F) <- -contr.sum(2)/2 # High = -0.5, Low = 0.5
      contrasts(GENDER) <- contr.sum(2)/2 # female = 0.5, male = -0.5
    })
  # Extract scaling values, i.e.,
  # enrollment full sample means and SDs
  scl <- sapply(
    c("AGE", "EDU.Y", "BMI", "SBTIV", help$subco$name, unique(help$hippo$name), help$psych$variable),
    function(i) {
      with(df, c(M = mean(get(i), na.rm = TRUE), SD = sd(get(i), na.rm = TRUE)))
    }) |> t()
  # Scale the variables
  df <- df |>
    mutate(
      across(
        .cols = all_of( rownames(scl) ),
        .fns = ~(.x - scl[cur_column(), "M"]) / scl[cur_column(), "SD"]
      )
    )
  # Return the data:
  get(return)
}
